# Generated by Django 3.1.2 on 2020-10-20 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
