# Generated by Django 3.1.2 on 2020-10-20 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_logs_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'verbose_name': 'User Log'},
        ),
    ]
