# Generated by Django 3.1.2 on 2020-10-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201020_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
