# Generated by Django 3.1.2 on 2020-10-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(default=0)),
                ('text', models.CharField(max_length=1500)),
                ('picture', models.ImageField(default='', upload_to='clues')),
                ('hiddenHTML', models.CharField(max_length=1500)),
                ('answer', models.CharField(max_length=150)),
            ],
        ),
    ]
