# Generated by Django 3.1.2 on 2020-10-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clues', '0002_auto_20201020_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='picture',
            field=models.ImageField(blank=True, default='', upload_to='clues'),
        ),
    ]
