# Generated by Django 3.1.2 on 2020-10-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clues', '0003_auto_20201020_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='no',
            field=models.IntegerField(default=1),
        ),
    ]
